# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8

# Enable parallel and daemon builds
org.gradle.parallel=true
org.gradle.daemon=true
# org.gradle.configureondemand=true

# Enable AndroidX
android.useAndroidX=true
android.enableJetifier=true

newArchEnabled=true
hermesEnabled=true

# Kotlin incremental compilation
kotlin.incremental=true
kotlin.code.style=official

# Suppress obsolete warnings from React Native
# android.suppressUnsupportedCompileSdk=35
